'use client'
import{doc,getDoc,setDoc,onSnapshot,type Unsubscribe}from 'firebase/firestore'
import{getFirestoreDb,isFirebaseConfigured}from './firebase'
export interface VitalThresholds{heartRateHigh:number;heartRateLow:number;spo2Low:number;systolicHigh:number;tempHigh:number;respRateHigh:number}
export interface AiConfig{systemInstructions:string;clinicalProtocols:string;model:string;temperature:number;maxTokens:number;isEnabled:boolean;vitalThresholds:VitalThresholds;lowStockThresholdPct:number;updatedAt:string;updatedBy:string}
export const DEFAULT_AI_CONFIG:AiConfig={systemInstructions:'You are a clinical decision-support AI in PRO Nurse HIS. Provide evidence-based guidance and risk flags. Recommend consulting a senior clinician for critical decisions. Never diagnose or prescribe.',clinicalProtocols:'EWS: 0=routine; 1-4=notify nurse; 5-6=urgent review 30min; 7+=emergency.\nCritical: HR<50/>120, SpO2<90%, SBP>180, Temp>38.5C, RR>25',model:'gemini-1.5-pro',temperature:0.3,maxTokens:2048,isEnabled:true,vitalThresholds:{heartRateHigh:120,heartRateLow:50,spo2Low:90,systolicHigh:180,tempHigh:38.5,respRateHigh:25},lowStockThresholdPct:100,updatedAt:new Date().toISOString(),updatedBy:'system'}
export async function seedAiConfig():Promise<void>{if(!isFirebaseConfigured())return;const r=doc(getFirestoreDb(),'system_settings','ai_config');if(!(await getDoc(r)).exists())await setDoc(r,DEFAULT_AI_CONFIG)}
export async function getAiConfig():Promise<AiConfig>{if(!isFirebaseConfigured())return DEFAULT_AI_CONFIG;try{const s=await getDoc(doc(getFirestoreDb(),'system_settings','ai_config'));if(s.exists())return s.data() as AiConfig;await seedAiConfig();return DEFAULT_AI_CONFIG}catch{return DEFAULT_AI_CONFIG}}
export function subscribeToAiConfig(cb:(c:AiConfig)=>void):Unsubscribe{if(!isFirebaseConfigured()){cb(DEFAULT_AI_CONFIG);return()=>{}};return onSnapshot(doc(getFirestoreDb(),'system_settings','ai_config'),s=>{cb(s.exists()?(s.data() as AiConfig):DEFAULT_AI_CONFIG)})}
export async function updateAiConfig(u:Partial<AiConfig>,by:string):Promise<void>{if(!isFirebaseConfigured())return;await setDoc(doc(getFirestoreDb(),'system_settings','ai_config'),{...u,updatedAt:new Date().toISOString(),updatedBy:by},{merge:true})}
