'use client'
import{collection,query,where,orderBy,limit,onSnapshot,addDoc,serverTimestamp}from 'firebase/firestore'
import{getFirestoreDb,isFirebaseConfigured}from './firebase'
import{getAiConfig,subscribeToAiConfig,type AiConfig}from './ai-config'
import{writeAuditLog}from './audit-logger'
async function gr(p:string,c:AiConfig):Promise<string>{if(!c.isEnabled)return '';try{const k=process.env.NEXT_PUBLIC_GEMINI_API_KEY;if(!k)return '';const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${c.model}:generateContent?key=${k}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({system_instruction:{parts:[{text:c.systemInstructions}]},contents:[{parts:[{text:p}]}],generationConfig:{temperature:c.temperature,maxOutputTokens:c.maxTokens}})});const d=await r.json();return d?.candidates?.[0]?.content?.parts?.[0]?.text??''}catch{return ''}}
async function push(a:Record<string,unknown>):Promise<void>{if(!isFirebaseConfigured())return;const db=getFirestoreDb();await addDoc(collection(db,'watchdog_alerts'),{...a,serverTime:serverTimestamp()});await addDoc(collection(db,'notifications'),{type:a.alertType,title:a.title,message:a.message,severity:a.severity,targetRoles:a.targetRoles,read:false,createdAt:a.createdAt??new Date().toISOString()})}
function wv(c:AiConfig):()=>void{const db=getFirestoreDb(),since=new Date(Date.now()-300000).toISOString(),q=query(collection(db,'vital_signs'),where('createdAt','>',since),orderBy('createdAt','desc'),limit(20)),seen=new Set<string>();return onSnapshot(q,async snap=>{for(const ch of snap.docChanges()){if(ch.type!=='added')continue;const id=ch.doc.id;if(seen.has(id))continue;seen.add(id);const d=ch.doc.data(),t=c.vitalThresholds,f:string[]=[];if(d.heartRate!==undefined&&(d.heartRate>t.heartRateHigh||d.heartRate<t.heartRateLow))f.push(`HR ${d.heartRate}bpm`);if(d.spo2!==undefined&&d.spo2<t.spo2Low)f.push(`SpO2 ${d.spo2}%`);if(d.systolic!==undefined&&d.systolic>t.systolicHigh)f.push(`BP ${d.systolic}`);if(d.temperature!==undefined&&d.temperature>t.tempHigh)f.push(`Temp ${d.temperature}C`);if(d.respRate!==undefined&&d.respRate>t.respRateHigh)f.push(`RR ${d.respRate}/min`);if(!f.length)continue;const msg=`CRITICAL VITALS for ${d.patientName??'Unknown'}: ${f.join(', ')}`;const rec=await gr(`${c.clinicalProtocols}\nVitals:${JSON.stringify(d)}\nFlags:${f.join(',')}\nBrief recommendation (2-3 sentences):`,c);await push({alertType:'critical_vitals',severity:'critical',title:'Critical Vital Signs',message:msg,recommendation:rec,patientId:d.patientId,targetRoles:['nurse','head_nurse','doctor','hospital_admin'],isRead:false,isResolved:false,triggeredBy:d.recordedBy??'system',createdAt:new Date().toISOString()});writeAuditLog({userId:d.recordedBy??'system',userName:d.recordedByName??'System',action:'AI_ALERT',collection:'vital_signs',docId:id,oldValue:null,newValue:{flags:f},module:'ai',timestamp:new Date().toISOString(),description:msg}).catch(console.error)}})
}
function ws():()=>void{const db=getFirestoreDb(),seen=new Set<string>();return onSnapshot(query(collection(db,'inventory'),where('lowStockAlert','==',true)),async snap=>{for(const ch of snap.docChanges()){if(ch.type==='removed')continue;const id=ch.doc.id;if(seen.has(id))continue;seen.add(id);const d=ch.doc.data();await push({alertType:'low_stock',severity:d.currentStock===0?'critical':'high',title:`Low Stock: ${d.name}`,message:`${d.name} has ${d.currentStock} units (min: ${d.minStock}). Restock required.`,targetRoles:['pharmacist','head_nurse','hospital_admin'],isRead:false,isResolved:false,triggeredBy:'system',createdAt:new Date().toISOString()})}})
}
let _u:Array<()=>void>=[]
export async function startAiWatchdog():Promise<()=>void>{if(!isFirebaseConfigured()||_u.length>0)return stopAiWatchdog;const c=await getAiConfig();if(!c.isEnabled)return()=>{};_u.push(wv(c),ws(),subscribeToAiConfig(cfg=>{if(!cfg.isEnabled)stopAiWatchdog()}));return stopAiWatchdog}
export function stopAiWatchdog():void{_u.forEach(f=>f());_u=[]}
