'use client'
import{collection,doc,getDoc,setDoc,runTransaction,serverTimestamp,increment}from 'firebase/firestore'
import{getFirestoreDb,isFirebaseConfigured}from './firebase'
import{auditBillingCharge}from './audit-logger'
import type{AuditModule}from './audit-logger'
export type BillingActionType='lab_order'|'medication_dispense'|'nursing_visit'|'vital_signs_recording'|'iv_cannulation'|'wound_dressing'|'icu_day'|'isolation_day'|'emergency_visit'|'equipment_use'|string
export interface BillingLine{id?:string;patientId:string;patientName:string;actionType:BillingActionType;description:string;qty:number;unitPrice:number;totalPrice:number;performedBy:string;performedByName:string;department:string;departmentId:string;module:AuditModule;timestamp:string;metadata?:Record<string,unknown>}
export interface PatientInvoice{id?:string;patientId:string;patientName:string;totalAmount:number;status:'open'|'pending_review'|'approved'|'paid'|'cancelled';currency:string;createdAt:string;updatedAt:string}
export const DEFAULT_PRICE_CATALOGUE:Record<string,number>={lab_order:150,medication_dispense:50,nursing_visit:80,vital_signs_recording:30,iv_cannulation:95,wound_dressing:70,icu_day:1500,isolation_day:800,emergency_visit:350,equipment_use:60}
export async function seedBillingPrices():Promise<void>{if(!isFirebaseConfigured())return;const db=getFirestoreDb();for(const[at,up]of Object.entries(DEFAULT_PRICE_CATALOGUE)){const ref=doc(db,'billing_prices',at);if(!(await getDoc(ref)).exists())await setDoc(ref,{actionType:at,unitPrice:up,currency:'SAR',description:at.replace(/_/g,' '),isActive:true,updatedAt:new Date().toISOString()})}}
export async function chargeBillingLine(line:Omit<BillingLine,'id'|'unitPrice'|'totalPrice'>&{unitPrice?:number}):Promise<string>{if(!isFirebaseConfigured())return 'offline';const db=getFirestoreDb(),ir=doc(db,'patient_invoices',line.patientId),pr=doc(db,'billing_prices',line.actionType),lr=collection(db,`patient_invoices/${line.patientId}/lines`);let lid='';await runTransaction(db,async tx=>{const ps=await tx.get(pr);const up:number=line.unitPrice??(ps.exists()?(ps.data().unitPrice as number):0);const tp=up*(line.qty??1);const is=await tx.get(ir);if(!is.exists())tx.set(ir,{patientId:line.patientId,patientName:line.patientName,totalAmount:tp,status:'open',currency:'SAR',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});else tx.update(ir,{totalAmount:increment(tp),updatedAt:new Date().toISOString()});const nlr=doc(lr);lid=nlr.id;tx.set(nlr,{...line,id:lid,unitPrice:up,totalPrice:tp,timestamp:line.timestamp??new Date().toISOString(),createdAt:serverTimestamp()})});auditBillingCharge(line.performedBy,line.performedByName,line.patientId,line.qty*(DEFAULT_PRICE_CATALOGUE[line.actionType]??0),line.description,line.module).catch(console.error);return lid}
export const chargeLabOrder=(pid:string,pn:string,lab:string,pb:string,pbn:string,d:string,di:string)=>chargeBillingLine({patientId:pid,patientName:pn,actionType:'lab_order',description:`Lab: ${lab}`,qty:1,performedBy:pb,performedByName:pbn,department:d,departmentId:di,module:'labs',timestamp:new Date().toISOString()})
export const chargeMedicationDispense=(pid:string,pn:string,med:string,qty:number,pb:string,pbn:string,d:string,di:string)=>chargeBillingLine({patientId:pid,patientName:pn,actionType:'medication_dispense',description:`Medication: ${med} x${qty}`,qty,performedBy:pb,performedByName:pbn,department:d,departmentId:di,module:'pharmacy',timestamp:new Date().toISOString()})
export const chargeNursingVisit=(pid:string,pn:string,desc:string,pb:string,pbn:string,d:string,di:string)=>chargeBillingLine({patientId:pid,patientName:pn,actionType:'nursing_visit',description:desc,qty:1,performedBy:pb,performedByName:pbn,department:d,departmentId:di,module:'nursing',timestamp:new Date().toISOString()})
