'use client'
import{useState,useEffect,useCallback}from 'react'
import{collection,query,where,orderBy,onSnapshot,addDoc,updateDoc,doc,serverTimestamp}from 'firebase/firestore'
import{getFirestoreDb,isFirebaseConfigured}from '@/lib/firebase'
export type TaskModule='nursing'|'pharmacy'|'labs'|'finance'|'admin'|'all'
export type TaskPriority='urgent'|'high'|'normal'|'low'
export type TaskStatus='pending'|'in_progress'|'completed'|'cancelled'
export interface PendingTask{id:string;title:string;description:string;module:TaskModule;priority:TaskPriority;assignedTo:string;department:string;departmentId:string;status:TaskStatus;patientId?:string;patientName?:string;dueAt?:string;createdBy:string;createdAt:string;completedAt?:string}
export function usePendingTasks(o:{departmentId?:string;userId?:string;module?:TaskModule;statusFilter?:TaskStatus[]}){const[tasks,setT]=useState<PendingTask[]>([]);const[loading,setL]=useState(true);const[error,setE]=useState<Error|null>(null);useEffect(()=>{if(!isFirebaseConfigured()){setL(false);return};const db=getFirestoreDb(),c=[];if(o.departmentId)c.push(where('departmentId','==',o.departmentId));if(o.module&&o.module!=='all')c.push(where('module','==',o.module));if(o.userId)c.push(where('assignedTo','==',o.userId));c.push(orderBy('createdAt','desc'));return onSnapshot(query(collection(db,'pending_tasks'),...c),snap=>{let r=snap.docs.map(d=>({id:d.id,...d.data()} as PendingTask));if(o.statusFilter?.length)r=r.filter(t=>o.statusFilter!.includes(t.status));setT(r);setL(false);setE(null)},e=>{setE(e);setL(false)})},[o.departmentId,o.userId,o.module,JSON.stringify(o.statusFilter)]);const createTask=useCallback(async(t:Omit<PendingTask,'id'>):Promise<string>=>{if(!isFirebaseConfigured())return 'offline';const r=await addDoc(collection(getFirestoreDb(),'pending_tasks'),{...t,createdAt:t.createdAt??new Date().toISOString(),serverTime:serverTimestamp()});return r.id},[]);const updateTaskStatus=useCallback(async(id:string,s:TaskStatus):Promise<void>=>{if(!isFirebaseConfigured())return;await updateDoc(doc(getFirestoreDb(),'pending_tasks',id),{status:s,...(s==='completed'?{completedAt:new Date().toISOString()}:{}),updatedAt:new Date().toISOString()})},[]);const completeTask=useCallback((id:string)=>updateTaskStatus(id,'completed'),[updateTaskStatus]);return{tasks,loading,error,createTask,updateTaskStatus,completeTask,pendingCount:tasks.filter(t=>t.status==='pending').length,urgentCount:tasks.filter(t=>t.status==='pending'&&t.priority==='urgent').length}}
